build:
  build:
    when:
      event: push
    image: 1and1internet/template-library-tools:giraffe
    pull: true
    auth_config:
      username: $$DOCKERHUB_USERNAME
      password: $$DOCKERHUB_PASSWORD
      email: $$DOCKERHUB_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 -u /scripts/images/build.py
  spectests:
    image: 1and1internet/ubuntu-16-rspec
    pull: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export export IMAGE=dronejob$CI_JOB_ID/${CI_REPO#*/}
      - echo $IMAGE
      - mkdir ../drone-tests; git clone https://github.com/1and1internet/drone-tests.git ../drone-tests
      - rspec -f documentation spec/spec_helper.rb
  publish:
    when:
      branch: master
      event: push
    image: 1and1internet/template-library-tools:giraffe
    auth_config:
     username: $$DOCKERHUB_USERNAME
     password: $$DOCKERHUB_PASSWORD
     email: $$DOCKERHUB_EMAIL
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $$SHARED_BUILD_STORAGE:/tmp/image-comparison
    environment:
     - DOCKERHUB_USERNAME=$$DOCKERHUB_USERNAME
     - DOCKERHUB_EMAIL=$$DOCKERHUB_EMAIL
     - DOCKERHUB_PASSWORD=$$DOCKERHUB_PASSWORD
     - DEPENDENCY_GRAPH_URL=$$DEPENDENCY_GRAPH_URL
     - DEPENDENCY_GRAPH_USERNAME=$$DEPENDENCY_GRAPH_USERNAME
     - DEPENDENCY_GRAPH_PASSWORD=$$DEPENDENCY_GRAPH_PASSWORD
     - BUILD_TRIGGER_API_URL=$$BUILD_TRIGGER_API_URL
     - BUILD_TRIGGER_API_USERNAME=$$BUILD_TRIGGER_API_USERNAME
     - BUILD_TRIGGER_API_PASSWORD=$$BUILD_TRIGGER_API_PASSWORD
     - TEMPLATE_UPDATER_URL=$$TEMPLATE_UPDATER_URL
     - TEMPLATE_UPDATER_USERNAME=$$TEMPLATE_UPDATER_USERNAME
     - TEMPLATE_UPDATER_PASSWORD=$$TEMPLATE_UPDATER_PASSWORD
     - SHARED_BUILD_STORAGE=$$SHARED_BUILD_STORAGE
    commands:
     - python3 -u /scripts/images/publish.py
