#!/bin/bash
set -eo pipefail
path="/tmp/policyd-cluebringer/cluebringer"
mysqld_safe  &
sleep 5
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS policyd;"
mysql -u root -p$MYSQL_ROOT_PASSWORD policyd < $path/database/policyd.mysql
mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown
