#!/bin/bash

set -eu

export CLUEBRINGER_DB_PASSWORD=${CLUEBRINGER_DB_PASSWORD:-ReplaceWithEnv}

envsubst < /tmpl/cluebringer/cluebringer.conf > /etc/cluebringer.conf
envsubst < /tmpl/cluebringer/cluebringer-webui.conf > /etc/cluebringer/cluebringer-webui.conf
